services:
  # Backend Service
  - type: web
    name: backend-service
    env: docker
    dockerfilePath: ./backend/Dockerfile  # Path to the backend Dockerfile
    buildCommand: ""  # Docker will automatically build using the Dockerfile
    startCommand: "python manage.py runserver 0.0.0.0:8000"  # Adjust to your backend framework command
    autoDeploy: true
    ports:
      - "8000:8000"  # Exposing port for backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket for Docker-in-Docker access (if required)
      - /tmp:/tmp  # Mount tmp directory

  # Frontend Service
  - type: web
    name: frontend-service
    env: docker
    dockerfilePath: ./front/Dockerfile  # Path to the frontend Dockerfile
    buildCommand: ""  # Docker will automatically build using the Dockerfile
    startCommand: "npm start"  # Adjust if your frontend requires a different start command (React/Vue/Angular/etc.)
    autoDeploy: true
    ports:
      - "8080:80"  # Exposing port for frontend (usually HTTP on port 80)
    dependsOn:
      - backend-service  # Ensure frontend starts after backend is up and running
